local vim_opts = require("core.utils.utils").vim_opts
vim.opt.shortmess:append("sIW")
vim_opts({
    opt = {
        showmode = false,
        signcolumn = "yes",
        numberwidth = 4,
        colorcolumn = "0",
        guicursor = "n-v-c-sm:block,i-ci-ve:ver25,r-cr-o:hor20",
        cursorline = true,
        cursorlineopt = "number",
        updatetime = 100,
        textwidth = 100,
        breakindent = true,
        breakindentopt = "shift:2,min:40,sbr",
        smartcase = true,
        ignorecase = true,
        foldmethod = "expr",
        foldexpr = "nvim_treesitter#foldexpr()",
        foldlevel = 99,
        foldlevelstart = 99,
        foldopen = "jump,block,hor,mark,percent,quickfix,search,tag,undo",
        foldenable = true,
        autowrite = true,
        autochdir = false,
        termguicolors = true,
        undofile = true,
        sessionoptions = "blank,buffers,curdir,folds,help,tabpages,winsize,winpos,terminal,localoptions",
        hidden = true,
        laststatus = 3,
        listchars = { space = '.', tab = '>>', eol = '↵' },
        background = 'dark',
        smarttab = false,
        number = true,
        relativenumber = true,
        expandtab = true,
        softtabstop = 4,
        tabstop = 4,
        shiftwidth = 4,
        signcolumn = 'yes',
        wrap = false,
        scrolloff = 8,
        hlsearch = true,
        confirm = true,
        linebreak = false,
    },
})
