vim.pack.add({
    "https://github.com/catppuccin/nvim",
    'https://github.com/sainnhe/everforest',
    "https://github.com/navarasu/onedark.nvim",
    'https://github.com/AlexvZyl/nordic.nvim',
    'https://github.com/EdenEast/nightfox.nvim',
    "https://github.com/folke/tokyonight.nvim",
    "https://github.com/rose-pine/neovim"
})
vim.cmd.colorscheme('catppuccin')
