import = [
    "~/.config/alacritty/themes/themes/nightfox.toml"
]

[window]
decorations = "None"
startup_mode = "Maximized"

[font]
normal = { family = "Agave Nerd Font", style = "Regular" }
size = 12.5

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
{ key = "n", mods = "Control|Shift", action = "CreateNewWindow"}
]
