import = [
    "~/repos/dotfiles/.config/alacritty/themes/themes/catppuccin.toml"
]

[shell]
program = 'fish'

[window]
startup_mode = "Maximized"
dynamic_title = true

[font]
normal = { family = "FantasqueSansM Nerd Font Mono", style = "Light" }
size = 10.5

[selection]
save_to_clipboard = true

[env]
WINIT_X11_SCALE_FACTOR = "1"
