import = [
    "~/repos/dotfiles/.config/alacritty/themes/themes/rose-pine.toml"
]
[shell]
program = 'fish'

[window]
startup_mode = "Maximized"
dynamic_title = true

[font]
normal = { family = "IosevkaSS05", style = "Regular" }
size = 10

[selection]
save_to_clipboard = true

