import = [
    "~/repos/dotfiles/.config/alacritty/themes/themes/carbonfox.toml"
]
[shell]
program = 'fish'

[window]
decorations = "None"
startup_mode = "Maximized"

[font]
normal = { family = "Agave Nerd Font", style = "Regular" }
size = 11

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
{ key = "n", mods = "Control|Shift", action = "CreateNewWindow"}
]
